// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/control/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioPath     string                 `protobuf:"bytes,2,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	SharedAtNanos int64                  `protobuf:"varint,3,opt,name=shared_at_nanos,json=sharedAtNanos,proto3" json:"shared_at_nanos,omitempty"`
	Immediate     bool                   `protobuf:"varint,4,opt,name=immediate,proto3" json:"immediate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackRequest) Reset() {
	*x = PlaybackRequest{}
	mi := &file_internal_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackRequest) ProtoMessage() {}

func (x *PlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackRequest.ProtoReflect.Descriptor instead.
func (*PlaybackRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *PlaybackRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *PlaybackRequest) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *PlaybackRequest) GetSharedAtNanos() int64 {
	if x != nil {
		return x.SharedAtNanos
	}
	return 0
}

func (x *PlaybackRequest) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

type PlaybackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackResponse) Reset() {
	*x = PlaybackResponse{}
	mi := &file_internal_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackResponse) ProtoMessage() {}

func (x *PlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackResponse.ProtoReflect.Descriptor instead.
func (*PlaybackResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *PlaybackResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PlaybackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlaybackCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioPath     string                 `protobuf:"bytes,2,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	SharedAtNanos int64                  `protobuf:"varint,3,opt,name=shared_at_nanos,json=sharedAtNanos,proto3" json:"shared_at_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackCommand) Reset() {
	*x = PlaybackCommand{}
	mi := &file_internal_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackCommand) ProtoMessage() {}

func (x *PlaybackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackCommand.ProtoReflect.Descriptor instead.
func (*PlaybackCommand) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *PlaybackCommand) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *PlaybackCommand) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *PlaybackCommand) GetSharedAtNanos() int64 {
	if x != nil {
		return x.SharedAtNanos
	}
	return 0
}

type PlaybackAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackAck) Reset() {
	*x = PlaybackAck{}
	mi := &file_internal_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackAck) ProtoMessage() {}

func (x *PlaybackAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackAck.ProtoReflect.Descriptor instead.
func (*PlaybackAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *PlaybackAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_internal_control_control_proto protoreflect.FileDescriptor

const file_internal_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/control/control.proto\x12\acontrol\"\x91\x01\n" +
	"\x0fPlaybackRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x02 \x01(\tR\taudioPath\x12&\n" +
	"\x0fshared_at_nanos\x18\x03 \x01(\x03R\rsharedAtNanos\x12\x1c\n" +
	"\timmediate\x18\x04 \x01(\bR\timmediate\"H\n" +
	"\x10PlaybackResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x0fPlaybackCommand\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x02 \x01(\tR\taudioPath\x12&\n" +
	"\x0fshared_at_nanos\x18\x03 \x01(\x03R\rsharedAtNanos\")\n" +
	"\vPlaybackAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\x95\x01\n" +
	"\vPeerControl\x12D\n" +
	"\rStartPlayback\x12\x18.control.PlaybackRequest\x1a\x19.control.PlaybackResponse\x12@\n" +
	"\x0eNotifyPlayback\x12\x18.control.PlaybackCommand\x1a\x14.control.PlaybackAckB\x19Z\x17silent/internal/controlb\x06proto3"

var (
	file_internal_control_control_proto_rawDescOnce sync.Once
	file_internal_control_control_proto_rawDescData []byte
)

func file_internal_control_control_proto_rawDescGZIP() []byte {
	file_internal_control_control_proto_rawDescOnce.Do(func() {
		file_internal_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)))
	})
	return file_internal_control_control_proto_rawDescData
}

var file_internal_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_control_control_proto_goTypes = []any{
	(*PlaybackRequest)(nil),  // 0: control.PlaybackRequest
	(*PlaybackResponse)(nil), // 1: control.PlaybackResponse
	(*PlaybackCommand)(nil),  // 2: control.PlaybackCommand
	(*PlaybackAck)(nil),      // 3: control.PlaybackAck
}
var file_internal_control_control_proto_depIdxs = []int32{
	0, // 0: control.PeerControl.StartPlayback:input_type -> control.PlaybackRequest
	2, // 1: control.PeerControl.NotifyPlayback:input_type -> control.PlaybackCommand
	1, // 2: control.PeerControl.StartPlayback:output_type -> control.PlaybackResponse
	3, // 3: control.PeerControl.NotifyPlayback:output_type -> control.PlaybackAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_control_control_proto_init() }
func file_internal_control_control_proto_init() {
	if File_internal_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_control_control_proto_goTypes,
		DependencyIndexes: file_internal_control_control_proto_depIdxs,
		MessageInfos:      file_internal_control_control_proto_msgTypes,
	}.Build()
	File_internal_control_control_proto = out.File
	file_internal_control_control_proto_goTypes = nil
	file_internal_control_control_proto_depIdxs = nil
}
