// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/control/control.proto

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PeerControl_StartPlayback_FullMethodName  = "/control.PeerControl/StartPlayback"
	PeerControl_NotifyPlayback_FullMethodName = "/control.PeerControl/NotifyPlayback"
)

// PeerControlClient is the client API for PeerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerControlClient interface {
	StartPlayback(ctx context.Context, in *PlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error)
	NotifyPlayback(ctx context.Context, in *PlaybackCommand, opts ...grpc.CallOption) (*PlaybackAck, error)
}

type peerControlClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerControlClient(cc grpc.ClientConnInterface) PeerControlClient {
	return &peerControlClient{cc}
}

func (c *peerControlClient) StartPlayback(ctx context.Context, in *PlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackResponse)
	err := c.cc.Invoke(ctx, PeerControl_StartPlayback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerControlClient) NotifyPlayback(ctx context.Context, in *PlaybackCommand, opts ...grpc.CallOption) (*PlaybackAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaybackAck)
	err := c.cc.Invoke(ctx, PeerControl_NotifyPlayback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerControlServer is the server API for PeerControl service.
// All implementations must embed UnimplementedPeerControlServer
// for forward compatibility.
type PeerControlServer interface {
	StartPlayback(context.Context, *PlaybackRequest) (*PlaybackResponse, error)
	NotifyPlayback(context.Context, *PlaybackCommand) (*PlaybackAck, error)
	mustEmbedUnimplementedPeerControlServer()
}

// UnimplementedPeerControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerControlServer struct{}

func (UnimplementedPeerControlServer) StartPlayback(context.Context, *PlaybackRequest) (*PlaybackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPlayback not implemented")
}
func (UnimplementedPeerControlServer) NotifyPlayback(context.Context, *PlaybackCommand) (*PlaybackAck, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyPlayback not implemented")
}
func (UnimplementedPeerControlServer) mustEmbedUnimplementedPeerControlServer() {}
func (UnimplementedPeerControlServer) testEmbeddedByValue()                     {}

// UnsafePeerControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerControlServer will
// result in compilation errors.
type UnsafePeerControlServer interface {
	mustEmbedUnimplementedPeerControlServer()
}

func RegisterPeerControlServer(s grpc.ServiceRegistrar, srv PeerControlServer) {
	// If the following call panics, it indicates UnimplementedPeerControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PeerControl_ServiceDesc, srv)
}

func _PeerControl_StartPlayback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaybackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerControlServer).StartPlayback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerControl_StartPlayback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerControlServer).StartPlayback(ctx, req.(*PlaybackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerControl_NotifyPlayback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaybackCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerControlServer).NotifyPlayback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerControl_NotifyPlayback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerControlServer).NotifyPlayback(ctx, req.(*PlaybackCommand))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerControl_ServiceDesc is the grpc.ServiceDesc for PeerControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.PeerControl",
	HandlerType: (*PeerControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartPlayback",
			Handler:    _PeerControl_StartPlayback_Handler,
		},
		{
			MethodName: "NotifyPlayback",
			Handler:    _PeerControl_NotifyPlayback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/control/control.proto",
}
