// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/control/control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioPath     string                 `protobuf:"bytes,2,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	SharedAtNanos int64                  `protobuf:"varint,3,opt,name=shared_at_nanos,json=sharedAtNanos,proto3" json:"shared_at_nanos,omitempty"`
	Immediate     bool                   `protobuf:"varint,4,opt,name=immediate,proto3" json:"immediate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackRequest) Reset() {
	*x = PlaybackRequest{}
	mi := &file_internal_control_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackRequest) ProtoMessage() {}

func (x *PlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackRequest.ProtoReflect.Descriptor instead.
func (*PlaybackRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{0}
}

func (x *PlaybackRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *PlaybackRequest) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *PlaybackRequest) GetSharedAtNanos() int64 {
	if x != nil {
		return x.SharedAtNanos
	}
	return 0
}

func (x *PlaybackRequest) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

type PlaybackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackResponse) Reset() {
	*x = PlaybackResponse{}
	mi := &file_internal_control_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackResponse) ProtoMessage() {}

func (x *PlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackResponse.ProtoReflect.Descriptor instead.
func (*PlaybackResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{1}
}

func (x *PlaybackResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PlaybackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PlaybackCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioId       string                 `protobuf:"bytes,1,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioPath     string                 `protobuf:"bytes,2,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	SharedAtNanos int64                  `protobuf:"varint,3,opt,name=shared_at_nanos,json=sharedAtNanos,proto3" json:"shared_at_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackCommand) Reset() {
	*x = PlaybackCommand{}
	mi := &file_internal_control_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackCommand) ProtoMessage() {}

func (x *PlaybackCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackCommand.ProtoReflect.Descriptor instead.
func (*PlaybackCommand) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{2}
}

func (x *PlaybackCommand) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *PlaybackCommand) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *PlaybackCommand) GetSharedAtNanos() int64 {
	if x != nil {
		return x.SharedAtNanos
	}
	return 0
}

type PlaybackAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaybackAck) Reset() {
	*x = PlaybackAck{}
	mi := &file_internal_control_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaybackAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaybackAck) ProtoMessage() {}

func (x *PlaybackAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaybackAck.ProtoReflect.Descriptor instead.
func (*PlaybackAck) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{3}
}

func (x *PlaybackAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type StreamPlaybackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AudioId       string                 `protobuf:"bytes,2,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	AudioPath     string                 `protobuf:"bytes,3,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	SharedAtNanos int64                  `protobuf:"varint,4,opt,name=shared_at_nanos,json=sharedAtNanos,proto3" json:"shared_at_nanos,omitempty"`
	Relay         bool                   `protobuf:"varint,5,opt,name=relay,proto3" json:"relay,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,6,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      uint32                 `protobuf:"varint,7,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleFormat  string                 `protobuf:"bytes,8,opt,name=sample_format,json=sampleFormat,proto3" json:"sample_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPlaybackRequest) Reset() {
	*x = StreamPlaybackRequest{}
	mi := &file_internal_control_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPlaybackRequest) ProtoMessage() {}

func (x *StreamPlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPlaybackRequest.ProtoReflect.Descriptor instead.
func (*StreamPlaybackRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{4}
}

func (x *StreamPlaybackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamPlaybackRequest) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *StreamPlaybackRequest) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *StreamPlaybackRequest) GetSharedAtNanos() int64 {
	if x != nil {
		return x.SharedAtNanos
	}
	return 0
}

func (x *StreamPlaybackRequest) GetRelay() bool {
	if x != nil {
		return x.Relay
	}
	return false
}

func (x *StreamPlaybackRequest) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *StreamPlaybackRequest) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *StreamPlaybackRequest) GetSampleFormat() string {
	if x != nil {
		return x.SampleFormat
	}
	return ""
}

type StreamPlaybackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPlaybackResponse) Reset() {
	*x = StreamPlaybackResponse{}
	mi := &file_internal_control_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPlaybackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPlaybackResponse) ProtoMessage() {}

func (x *StreamPlaybackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPlaybackResponse.ProtoReflect.Descriptor instead.
func (*StreamPlaybackResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{5}
}

func (x *StreamPlaybackResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StreamPlaybackResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamPlaybackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FollowerId    string                 `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	SharedAtNanos int64                  `protobuf:"varint,3,opt,name=shared_at_nanos,json=sharedAtNanos,proto3" json:"shared_at_nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinStreamRequest) Reset() {
	*x = JoinStreamRequest{}
	mi := &file_internal_control_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinStreamRequest) ProtoMessage() {}

func (x *JoinStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinStreamRequest.ProtoReflect.Descriptor instead.
func (*JoinStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{6}
}

func (x *JoinStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinStreamRequest) GetFollowerId() string {
	if x != nil {
		return x.FollowerId
	}
	return ""
}

func (x *JoinStreamRequest) GetSharedAtNanos() int64 {
	if x != nil {
		return x.SharedAtNanos
	}
	return 0
}

type JoinStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Attempted     uint32                 `protobuf:"varint,4,opt,name=attempted,proto3" json:"attempted,omitempty"`
	Succeeded     uint32                 `protobuf:"varint,5,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinStreamResponse) Reset() {
	*x = JoinStreamResponse{}
	mi := &file_internal_control_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinStreamResponse) ProtoMessage() {}

func (x *JoinStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinStreamResponse.ProtoReflect.Descriptor instead.
func (*JoinStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{7}
}

func (x *JoinStreamResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinStreamResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *JoinStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JoinStreamResponse) GetAttempted() uint32 {
	if x != nil {
		return x.Attempted
	}
	return 0
}

func (x *JoinStreamResponse) GetSucceeded() uint32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_internal_control_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{8}
}

func (x *StopStreamRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopStreamRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StopStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_internal_control_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{9}
}

func (x *StopStreamResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *StopStreamResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AudioChunk struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SessionId             string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AudioId               string                 `protobuf:"bytes,2,opt,name=audio_id,json=audioId,proto3" json:"audio_id,omitempty"`
	Sequence              int64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data                  []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	EndOfStream           bool                   `protobuf:"varint,5,opt,name=end_of_stream,json=endOfStream,proto3" json:"end_of_stream,omitempty"`
	SentAtNanos           int64                  `protobuf:"varint,6,opt,name=sent_at_nanos,json=sentAtNanos,proto3" json:"sent_at_nanos,omitempty"`
	ProducedAtNanos       int64                  `protobuf:"varint,7,opt,name=produced_at_nanos,json=producedAtNanos,proto3" json:"produced_at_nanos,omitempty"`
	SequenceDiscontinuity bool                   `protobuf:"varint,8,opt,name=sequence_discontinuity,json=sequenceDiscontinuity,proto3" json:"sequence_discontinuity,omitempty"`
	NextSequence          int64                  `protobuf:"varint,9,opt,name=next_sequence,json=nextSequence,proto3" json:"next_sequence,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_internal_control_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_control_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_internal_control_control_proto_rawDescGZIP(), []int{10}
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetAudioId() string {
	if x != nil {
		return x.AudioId
	}
	return ""
}

func (x *AudioChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetEndOfStream() bool {
	if x != nil {
		return x.EndOfStream
	}
	return false
}

func (x *AudioChunk) GetSentAtNanos() int64 {
	if x != nil {
		return x.SentAtNanos
	}
	return 0
}

func (x *AudioChunk) GetProducedAtNanos() int64 {
	if x != nil {
		return x.ProducedAtNanos
	}
	return 0
}

func (x *AudioChunk) GetSequenceDiscontinuity() bool {
	if x != nil {
		return x.SequenceDiscontinuity
	}
	return false
}

func (x *AudioChunk) GetNextSequence() int64 {
	if x != nil {
		return x.NextSequence
	}
	return 0
}

var File_internal_control_control_proto protoreflect.FileDescriptor

const file_internal_control_control_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/control/control.proto\x12\acontrol\"\x91\x01\n" +
	"\x0fPlaybackRequest\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x02 \x01(\tR\taudioPath\x12&\n" +
	"\x0fshared_at_nanos\x18\x03 \x01(\x03R\rsharedAtNanos\x12\x1c\n" +
	"\timmediate\x18\x04 \x01(\bR\timmediate\"H\n" +
	"\x10PlaybackResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"s\n" +
	"\x0fPlaybackCommand\x12\x19\n" +
	"\baudio_id\x18\x01 \x01(\tR\aaudioId\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x02 \x01(\tR\taudioPath\x12&\n" +
	"\x0fshared_at_nanos\x18\x03 \x01(\x03R\rsharedAtNanos\")\n" +
	"\vPlaybackAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\x90\x02\n" +
	"\x15StreamPlaybackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\baudio_id\x18\x02 \x01(\tR\aaudioId\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x03 \x01(\tR\taudioPath\x12&\n" +
	"\x0fshared_at_nanos\x18\x04 \x01(\x03R\rsharedAtNanos\x12\x14\n" +
	"\x05relay\x18\x05 \x01(\bR\x05relay\x12\x1f\n" +
	"\vsample_rate\x18\x06 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\a \x01(\rR\bchannels\x12#\n" +
	"\rsample_format\x18\b \x01(\tR\fsampleFormat\"m\n" +
	"\x16StreamPlaybackResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"{\n" +
	"\x11JoinStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfollower_id\x18\x02 \x01(\tR\n" +
	"followerId\x12&\n" +
	"\x0fshared_at_nanos\x18\x03 \x01(\x03R\rsharedAtNanos\"\xa5\x01\n" +
	"\x12JoinStreamResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\tattempted\x18\x04 \x01(\rR\tattempted\x12\x1c\n" +
	"\tsucceeded\x18\x05 \x01(\rR\tsucceeded\"J\n" +
	"\x11StopStreamRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"i\n" +
	"\x12StopStreamResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc6\x02\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\baudio_id\x18\x02 \x01(\tR\aaudioId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x03R\bsequence\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\"\n" +
	"\rend_of_stream\x18\x05 \x01(\bR\vendOfStream\x12\"\n" +
	"\rsent_at_nanos\x18\x06 \x01(\x03R\vsentAtNanos\x12*\n" +
	"\x11produced_at_nanos\x18\a \x01(\x03R\x0fproducedAtNanos\x125\n" +
	"\x16sequence_discontinuity\x18\b \x01(\bR\x15sequenceDiscontinuity\x12#\n" +
	"\rnext_sequence\x18\t \x01(\x03R\fnextSequence2\xd1\x03\n" +
	"\vPeerControl\x12D\n" +
	"\rStartPlayback\x12\x18.control.PlaybackRequest\x1a\x19.control.PlaybackResponse\x12@\n" +
	"\x0eNotifyPlayback\x12\x18.control.PlaybackCommand\x1a\x14.control.PlaybackAck\x12V\n" +
	"\x13StartStreamPlayback\x12\x1e.control.StreamPlaybackRequest\x1a\x1f.control.StreamPlaybackResponse\x12M\n" +
	"\x12JoinStreamPlayback\x12\x1a.control.JoinStreamRequest\x1a\x1b.control.JoinStreamResponse\x12M\n" +
	"\x12StopStreamPlayback\x12\x1a.control.StopStreamRequest\x1a\x1b.control.StopStreamResponse\x12D\n" +
	"\vStreamAudio\x12\x1e.control.StreamPlaybackRequest\x1a\x13.control.AudioChunk0\x01B\x19Z\x17silent/internal/controlb\x06proto3"

var (
	file_internal_control_control_proto_rawDescOnce sync.Once
	file_internal_control_control_proto_rawDescData []byte
)

func file_internal_control_control_proto_rawDescGZIP() []byte {
	file_internal_control_control_proto_rawDescOnce.Do(func() {
		file_internal_control_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)))
	})
	return file_internal_control_control_proto_rawDescData
}

var file_internal_control_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_control_control_proto_goTypes = []any{
	(*PlaybackRequest)(nil),        // 0: control.PlaybackRequest
	(*PlaybackResponse)(nil),       // 1: control.PlaybackResponse
	(*PlaybackCommand)(nil),        // 2: control.PlaybackCommand
	(*PlaybackAck)(nil),            // 3: control.PlaybackAck
	(*StreamPlaybackRequest)(nil),  // 4: control.StreamPlaybackRequest
	(*StreamPlaybackResponse)(nil), // 5: control.StreamPlaybackResponse
	(*JoinStreamRequest)(nil),      // 6: control.JoinStreamRequest
	(*JoinStreamResponse)(nil),     // 7: control.JoinStreamResponse
	(*StopStreamRequest)(nil),      // 8: control.StopStreamRequest
	(*StopStreamResponse)(nil),     // 9: control.StopStreamResponse
	(*AudioChunk)(nil),             // 10: control.AudioChunk
}
var file_internal_control_control_proto_depIdxs = []int32{
	0,  // 0: control.PeerControl.StartPlayback:input_type -> control.PlaybackRequest
	2,  // 1: control.PeerControl.NotifyPlayback:input_type -> control.PlaybackCommand
	4,  // 2: control.PeerControl.StartStreamPlayback:input_type -> control.StreamPlaybackRequest
	6,  // 3: control.PeerControl.JoinStreamPlayback:input_type -> control.JoinStreamRequest
	8,  // 4: control.PeerControl.StopStreamPlayback:input_type -> control.StopStreamRequest
	4,  // 5: control.PeerControl.StreamAudio:input_type -> control.StreamPlaybackRequest
	1,  // 6: control.PeerControl.StartPlayback:output_type -> control.PlaybackResponse
	3,  // 7: control.PeerControl.NotifyPlayback:output_type -> control.PlaybackAck
	5,  // 8: control.PeerControl.StartStreamPlayback:output_type -> control.StreamPlaybackResponse
	7,  // 9: control.PeerControl.JoinStreamPlayback:output_type -> control.JoinStreamResponse
	9,  // 10: control.PeerControl.StopStreamPlayback:output_type -> control.StopStreamResponse
	10, // 11: control.PeerControl.StreamAudio:output_type -> control.AudioChunk
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_internal_control_control_proto_init() }
func file_internal_control_control_proto_init() {
	if File_internal_control_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_control_control_proto_rawDesc), len(file_internal_control_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_control_control_proto_goTypes,
		DependencyIndexes: file_internal_control_control_proto_depIdxs,
		MessageInfos:      file_internal_control_control_proto_msgTypes,
	}.Build()
	File_internal_control_control_proto = out.File
	file_internal_control_control_proto_goTypes = nil
	file_internal_control_control_proto_depIdxs = nil
}
